name: toy-object-detector
channels:
- defaults
dependencies:
- cython=0.28.5
- h5py>=2.7,<3
- hdf5>=1.8,<2
- numpy>=1.13.1
- pip>=9.0.1,<=18.1
- python=3.6
- scipy=0.19.1
- scikit-image==0.14.0
- pip:
  - git+https://github.com/fizyr/keras-retinanet.git#078e12d87ecc9422f525965c0dc1a9478117c480
  - git+https://github.com/iver56/generate-shapes.git
  - tensorflow-gpu==1.11.0
