name: toy-object-detector
channels:
- defaults
dependencies:
- h5py=2.7.0
- hdf5=1.8.15.1
- numpy
- pip=9.0.1
- python=3.6.2
- scipy=0.19.1
- scikit-image
- pip:
  - git+https://github.com/iver56/keras-retinanet.git
  - git+https://github.com/iver56/generate-shapes.git
  - tensorflow-gpu==1.7.0
